language: python

python: 
  - "3.4"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3 python python-dev python3-pip python-virtualenv git python3-tk

install:
  - sudo pip install -r requirements.txt

script:
  - sudo make test