version: '3'
services:

  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  redis:
    image: "redis:alpine"
    depends_on:
      - web
    networks:
      - net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  networks:
    net: