version: '3.7'
services:

  # db:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   networks:
  #     - net
  #   deploy:
  #     placement: 
  #       constraints: [node.role == worker]
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - net
    deploy:
      placement: 
        constraints: [node.role == manager]

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: tiptabs_backend:latest
    ports:
     - "5000:5000"
    networks:
      - net
    deploy:
      # placement: 
      #   constraints: [node.role == worker]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  # frontend:
  #   image: tiptabs_frontend
  #   depends_on:
  #    - backend
  #    - db
  #   ports:
  #    - 80:80
  #   networks:
  #     - net
  #   deploy:
  #     placement: 
  #       constraints: [node.role == worker]
  #     replicas: 2
  #     update_config:
  #       parallelism: 2
  #       delay: 10s
  #     restart_policy:
  #       condition: on-failure
    
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
     - "8181:8080"
    networks:
      - net
    stop_grace_period: 1m30s
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement: 
        constraints: [node.role == manager]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  
networks:
  net:
