version: '3'
services:

  web:
    build: .
    ports:
     - "5000:5000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  redis:
    image: "redis:alpine"
    depends_on:
      - web
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  networks:
    frontend:
    backend: